---
title: "Assignment6"
author: "Seth Pottle"
date: "November 17, 2018"
output: html_document
runtime: shiny
editor_options:
  chunk output type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(shiny)
library(fivethirtyeight)
library(ggiraph)
```


```{r echo=F}
div(style='display:inline-block', selectInput(inputId = 'xaxis', "X Variable:", names(bad_drivers), selected = 'perc_speeding'))

div(style='display:inline-block', selectInput(inputId = 'yaxis', "Y Variable:", names(bad_drivers), selected = 'perc_alcohol'))

div(style='display:inline-block', selectInput(inputId = 'dotSize', "Dot Size:", names(bad_drivers), selected = 'perc_alcohol'))

div(style='display:inline-block', textInput(inputId = 'state', "Selected State:", value = "Louisiana"))
```



```{r echo=F}
renderGirafe({
  selected_state <- ifelse(bad_drivers$state %in% input$state, 'selected', 'NA')
  
  plot <- ggplot(data = bad_drivers, aes_string(x = input$xaxis, y = input$yaxis, size = input$dotSize, tooltip = 'state')) +
    geom_point_interactive(aes(color = selected_state)) +
    scale_color_discrete(guide = 'none') +
    ggtitle('Insurance Premiums Data')

  girafe(ggobj = plot, width = .7)
})
```

