---
title: "Terrorism in Europe"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
```

```{r}
dt <- read_csv(file = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/terrorism/eu_terrorism_fatalities_by_country.csv')

#use  gather() to transform `dt` in a longitudinal dataset and save it to dtYear 
dtYear <- dt %>% gather(key = 'country', value = 'casualties', -iyear)
#use dtYear to create a dataset total casualties by state and save it to dt
dt <- dtYear %>% group_by(country) %>% summarise(total = sum(casualties))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Europe

```{r}
ggplot(data = dt) +
  geom_col(aes(x = country, total))
```

Column {data-width=350}
-----------------------------------------------------------------------

### State 1

```{r}

casualty <- function(x, y) {
  x %>%
    filter(country == y) %>%
    ggplot() +
    geom_line(aes(x = iyear, y = casualties))
}
casualty(dtYear, 'Belgium')

```

### State 2

```{r}

casualty(dtYear, 'France')

```

